name: Ion Docs
title: Amazon Ion
lang: en
baseurl: /ion-docs
markdown: kramdown
kramdown:
  input: GFM
  toc_levels: "2,3" 
highlighter: rouge
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
plugins:
  - jekyll-redirect-from

# Don't clobber things built into ./_site/books by our MdBookGenerator plugin
keep_files:
  - books
