[[sec:glossary]]
[glossary]
= Glossary

[glossary]

actual arity::
The number of subforms (arguments or argument groups) in a macro invocation.
A macro can be _fixed arity_ or _variable arity_.

argument::
A single sub-expression within a macro invocation, corresponding to one of the macro’s
parameters.  This is by default a one-to-one relation, but a parameter’s grouping mode
can change this to a many-to-one relation.

argument group::
The concrete syntax for a _grouped parameter_.
In a macro invocation, a list containing multiple arguments, delimited explicitly with `[...]`
notation in Ion text. Used to express parameters that accept more than one argument.

cardinality::
Describes the number of values that a parameter will accept when the macro is invoked.
One of zero-or-one, exactly-one, zero-or-more, or one-or-more.
Specified in a signature by one of the modifiers `*?*`, `*!*`, `*{asterisk}*`, `*+*`, `*\...*`
or `*\...+*`.

declaration::
The association of a name with an entity (for example, a module or macro). See also _definition_. Not
all declarations are definitions: some introduce new names for existing entities.

definition::
The specification of a new entity.

directive::
A keyword or unit of data in an Ion document that affects the encoding environment, and thus the
way the document’s data is decoded.
In Ion 1.0 there are two directives: _Ion version markers_, and the _symbol table directives_.
Ion 1.1 adds _encoding directives_.

document::
A stream of octets conforming to either the Ion text or binary specification. Can consist of
multiple _segments_, perhaps using varying versions of the Ion specification. A document doesn’t
necessarily exist as a file, and isn’t necessarily finite.

E-expression::
See _encoding expression_.

encoding directive::
In an Ion 1.1 segment, a top-level struct annotated with `$ion_encoding`.
Defines a new encoding environment for the segment immediately following it.
The _symbol table directive_ is effectively a less capable alternative syntax.

encoding environment::
The context-specific data maintained by an Ion implementation while encoding or decoding data. In
Ion 1.0 this consists of the current symbol table; in Ion 1.1 this is expanded to also include the Ion
spec version, the current macro table, and a collection of available modules.

encoding expression::
The invocation of a macro in encoded data, aka E-expression. Starts with a macro reference
denoting the function to invoke. The Ion text format uses “smile syntax” `(:__macro__ …)` to denote
E-expressions. Ion binary devotes a large number of opcodes to E-expressions, so they can be
compact.

fixed arity::
Describes a macro without optional or rest parameters, so invocations must have actual arity that
equals the macro’s formal arity.

formal arity::
The number of parameters declared by a macro.  Due to _optional parameters_ and _rest parameters_,
the _actual arity_ of a macro invocation may differ from its formal arity.

grouped parameter::
A macro parameter that accepts multiple arguments in an _argument group_ when the macro is
invoked.
See also _grouping mode_.

grouping mode::
One of three ways that a macro parameter is given arguments. A _simple parameter_ accepts one
argument, a _grouped parameter_ accepts a list of arguments, and a _rest parameter_ accepts
“all the rest” of the trailing arguments without a grouping list.

Ion version marker::
A keyword directive that denotes the start of a new segment encoded with a specific Ion version.
Also known as “IVM”.

macro::
A transformation function that accepts some number of streams of values, and produces a stream of
values.

macro definition::
Specifies a macro in terms of a _signature_ and a _template_.

macro reference::
Identifies a macro for invocation, alias, or exporting. Must always be unambiguous. Lexically
scoped, and never a “forward reference” to a macro that’s declared later in the document.

module::
The data entity that defines and exports both symbols and macros. Modules are imported by
encoding directives then installed into the local symbol and/or macro tables.

optional parameter::
A parameter that can have its corresponding subform(s) omitted when the macro is invoked.
A parameter is optional if it is _voidable_ and all following arguments are also voidable.

parameter::
A named input to a macro, as defined by its signature. At expansion time a parameter produces a
stream of values.

qualified macro reference::
A macro reference that consists of a module name and either a macro name exported by that module,
or a numeric address within the range of the module’s exported macro table. In text, these look
like `:__module-name__:__name-or-address__`.

quasi-literal::
A template, denoted as a list or struct, that is _partly_ (“quasi-”) literal.
List-shaped templates treat the elements as nested templates.
Struct-shaped templates treat the field names as literal, but the corresponding values as
templates.
S-expressions denote operator invocations and are not treated quasi-literally.

rest parameter::
A macro parameter—always the final parameter—declared with the `*\...*` or `*\...+*` modifier,
that accepts all remaining arguments to the macro as if they were in an implicit _argument group_.
Similar to “varargs” parameters in Java and other languages.
See also _grouping mode_.

segment::
A contiguous partition of a document that uses the same encoding environment. Segment boundaries
are caused by directives: an IVM starts a new segment, while `$ion_symbol_table` and `$ion_encoding`
directives end segments (with a new one starting immediately afterwards).

signature::
The part of a macro definition that specifies its “calling convention”, in terms of the shape,
type, and cardinality of arguments it accepts, and the type and cardinality of the results it
produces.

simple parameter::
A macro parameter that matches a single argument when the macro is invoked.
See also _grouping mode_.

subform::
A nested portion within some syntactic form of the module or macro declarations.

symbol table directive::
A top-level struct annotated with `$ion_symbol_table`.  Defines a new encoding environment
without any macros.  Valid in Ion 1.0 and 1.1.

system symbol::
A symbol provided by the Ion implementation via the system module `$ion`.
System symbols are available at all points within an Ion document, though the selection of symbols
varies by segment according to its Ion version.

system macro::
A macro provided by the Ion implementation via the system module `$ion`.
System macros are available at all points within Ion 1.1 segments.

system module::
A standard module named `$ion` that is provided by the Ion implementation, implicitly installed so
that the system symbols and system macros are available at all points within a document.
Subsumes the functionality of the Ion 1.0 system symbol table.

template::
The part of a macro definition that expresses its transformation of inputs to results.

unqualified macro reference::
A macro reference that consists of either a macro name or numeric address, without a qualifying
module name. These are resolved using lexical scope and must always be unambiguous.

variable arity::
Describes a macro with optional and/or rest parameters, so invocations may have actual arity
different from the macro’s formal arity.

void::
An empty stream of values. Produced by the system macro `void` as in the E-expression `(:void)`.

voidable::
Describes a parameter that accepts void, aka the empty stream.
Such parameters have cardinality zero-or-one or zero-or-more.
