[[sec:glossary]]
[glossary]
= Glossary

[glossary]

arity::
The number of arguments declared by or passed to a macro.  A macro can be _fixed_ or _variable_
arity; the number of subforms in an invocation is its _actual arity_.

argument::
A single subform within an encoding expression, corresponding to one of the macro’s parameters.
This is a one-to-one relation except in the case of rest parameters, where any number of trailing
arguments are passed to the same parameter.

cardinality::
The number of elements accepted by a single argument of a macro, or produced by a macro. The
arguments and results of a macro are streams, and each can be constrained to have exactly-one
(`*!*`), zero-or-one (`*?*`), zero-or-more (`*{asterisk}*`, `*\...*`), or one-or-more (`*+*`)
elements.

declaration::
The association of a name with an entity (for example, a module or macro). See also _definition_. Not
all declarations are definitions: some introduce new names for existing entities.

definition::
The specification of a new entity. Most (but not all) definitions are declarations.

directive::
A unit of data in an Ion document that affects the encoding context, and thus the way the
document’s data is decoded. In Ion 1.0 there are two directives: the Ion Version Marker, and
top-level `$ion_symbol_table` structs. Ion 1.1 adds the `$ion_encoding` directive.

document::
A stream of octets conforming to either the Ion text or binary specification. Can consist of
multiple _segments_, perhaps using varying versions of the Ion specification. A document doesn’t
necessarily exist as a file, and isn’t necessarily finite.

E-expression::
See _encoding expression_.

encoding directive::
In Ion 1.1, a top-level `$ion_encoding` struct that controls the segment immediately following it.
The 1.0 `$ion_symbol_table` directive is effectively a less capable alternative syntax.

encoding environment::
The context-specific data maintained by an Ion implementation while encoding or decoding data. In
Ion 1.0 this consists of the local symbol table; in Ion 1.1 it also has the local module table
and a collection of available modules.

encoding expression::
The invocation of a macro in encoded data, aka E-expression. Starts with a macro reference
denoting the function to invoke. The Ion text format uses “smile syntax” `(:__macro__ …)` to denote
E-expressions. Ion binary devotes a large number of opcodes to E-expressions, so they can be
compact.

macro::
A transformation function that accepts some number of streams of values, and produces a stream of
values.

macro definition::
Specifies a macro in terms of a _signature_ and a _template_.

macro reference::
Identifies a macro for invocation, renaming, or exporting. Must always be unambiguous. Lexically
scoped, and never a “forward reference” to a macro that’s declared later in the document.

module::
The data entity that defines and exports both symbols and macros. Modules are imported by
encoding directives then installed into the local symbol and/or macro tables.

parameter::
A named input to a macro, as defined by its signature. At expansion time a parameter produces a
stream of values.

qualified macro reference::
A macro reference that consists of a module name and either a macro name exported by that module,
or a numeric address within the range of the module’s exported macro table. In text, these look
like `:__module-name__:__name-or-address__`.

rest parameter::
A macro parameter—always the final parameter—declared with the `*\...*` modifier, that accepts all
remaining arguments to the macro. Similar to “varargs” parameters in Java and other languages.

segment::
A contiguous portion of a document that uses the same encoding environment. Segment boundaries
are caused by directives: an IVM starts a new segment, while `$ion_symbol_table` and `$ion_encoding`
directives end segments (with a new one starting immediately afterwards).

signature::
The part of a macro definition that specifies its “calling convention”, in terms of the shape,
type, and cardinality of arguments it accepts, and the type and cardinality of the results it
produces.

system macro::
A macro provided by the Ion implementation via the system module `$ion`.
System macros are available at all points within Ion 1.1 segments.

system module::
A standard module named `$ion` that is provided by the Ion implementation, implicitly installed so
that the system symbols and system macros are available at all points within a document.
Subsumes the functionality of the Ion 1.0 system symbol table.

template::
The part of a macro definition that expresses its transformation of inputs to results.

unqualified macro reference::
A macro reference that consists of either a macro name or numeric address, without a qualifying
module name. These are resolved using lexical scope and must always be unambiguous.

void::
An empty stream of values. Produced by the system macro `void` as in the E-expression `(:void)`.

voidable::
Describes a parameter that accepts void, aka the empty stream.
Such parameters have zero-or-one (`*?*`), zero-or-more (`*{asterisk}*`, `*\...*`) cardinality.
