[[sec:macroexample]]
== Macros by Example

:mrk: subs="+normal"


Before getting into the technical details of Ion’s macro and module system, it’ll help to be more
familiar with the _use_ of macros.  We’ll step through increasingly sophisticated use cases, some
admittedly synthetic for illustrative purposes, with the intent of teaching the core concepts and
moving parts without getting into the weeds of more formal specification.


=== Constants

The most basic macro is a constant:


[{mrk}]
----
(*public* pi []
  3.141592653589793)
----

This declaration—taken recklessly out of context to keep things simple—defines a public macro
named `pi`.  The `[]` is the macro’s signature, in this case a trivial one that declares no
parameters.  The macro therefore accepts no arguments and always returns the obvious value.

To use this macro in a document, we write an _encoding expression_, aka E-expression:

[{mrk}]
----
*$ion_1_1*
(:pi)
----

The syntax `(:pi)` looks a lot like an S-expression.  It’s not, though, since colons
cannot appear unquoted in that context.  Ion 1.1 makes use of what’s invalid syntax in Ion
1.0—specifically, the `(:` digraph—to denote E-expressions.  Those characters must be followed by
a reference to a macro, and we say that the E-expression is an invocation of the macro.  Here,
`(:pi)` is an invocation of the macro named `pi`.

NOTE: We also call these “smile expressions” when we’re feeling particularly casual.

That document is equivalent to the following, in the sense that they denote the same data:

[{mrk}]
----
*$ion_1_1*
3.141592653589793
----

The process by which the Ion implementation turns the former document into the latter is called
_macro expansion_ or just _expansion_.  This happens automatically and (largely) invisibly to
Ion-consuming applications: the stream of values in both cases are the same.  The documents have
the same content, encoded in two different ways.  It’s reasonable to think of `(:pi)` as a custom
encoding for `3.141592653589793`, and the notation’s similarity to S-expressions leads us to the
term “encoding expression”.

NOTE: Any Ion 1.1 document with macros can be fully-expanded into an equivalent Ion 1.0 document.

We’ll streamline future examples with a couple conventions.  First, assume that any E-expression
is occurring within an Ion 1.1 document; due to the unquoted colon, that form is a syntax error
in Ion 1.0 context! Second, we’ll use the relation ⇒ to mean “expands to”, so we can say:

----
(:pi) ⇒ 3.141592653589793
----


=== Simple Templates

Most macros are of course non-constant.  Since macros are mathematically functional, this implies
that they can accept inputs that determine their results.

[{mrk}]
----
(*public* price
  [a, c]                          // signature
  { amount: a, currency: c })     // template
----
----
(:price 99 USD) ⇒ { amount: 99, currency: USD }
----

This macro has a non-trivial signature that declares two parameters, named `a` and `c`, and it
therefore accepts two arguments when invoked.

NOTE: For reasons that will soon be more clear, we will be careful to distinguish between the
views from “inside” and “outside” the macro: _parameters_ are the names used by a macro’s
implementation to refer to its expansion-time inputs, while _arguments_ are the data provided to a
macro at the point of invocation. In other words, we have “formal” parameters and “actual”
arguments.

Compared to the constant `pi` above, the body of this macro is suddenly interesting.  The struct
therein is our first non-trivial _template_, an expression in Ion’s new domain-specific language
for defining macro functions.  This expression language treats Ion scalar values (except for
symbols) as literals, giving the decimal in ``pi``’s template its intended meaning.  Expressions
that are structs are interpreted as quasi-literals: the field names are literal, but the field
“values” are arbitrary expressions.  This is why the `amount` and `currency` field names show up
as-is in the expansion.  The sub-expressions in this template demonstrate that the expression
language treats symbols as variable references.  Here, `a` and `c` in the template refer to the
parameters of the macro, and during expansion they are “filled in” with the values supplied by
the invoking E-expression.

The template language also treats lists quasi-literally, and every element inside the list is an
expression.  Here’s a silly macro to illustrate:

[{mrk}]
----
(*public* reverse [a, b] [b, a])
----
----
(:reverse first {amount:a, currency:c}) ⇒ [{amount:a, currency:c}, first]
----

To point out what may be obvious, note that the `a` in the E-expression is _not_ part of the
expression language and not a reference to the macro’s first parameter or any other named entity.
From the point of view of ``reverse``’s template, the input struct is literal data.

E-expressions can nest, so we could also encode the same data using `price`:

----
(:reverse first (:price a c)) ⇒ [{amount:a, currency:c}, first]
----


=== Invoking Macros from Templates

So the template language treats symbols as parameter references, other scalars as literals, and
structs and lists as quasi-literals, but what about S-expressions?

[{mrk}]
----
(*public* website_url
  [path]
  (make_string "https://www.amazon.com/" path))
----

Template expressions that are S-expressions are operator invocations, where the operators are
either special forms or macro invocations.  In this case, it’s the latter: an invocation of the
system macro (_i.e._, built-in function) `make_string`, which concatenates its arguments to produce
a single string:

----
(:website_url "gp/cart") ⇒ "https://www.amazon.com/gp/cart"
----

In the template language, macro invocations can appear almost anywhere:

[{mrk}]
----
(*public* detail_page_url
  [asin]
  (website_url (make_string "dp/" asin)))
----
----
(:detail_page_url "B08KTZ8249") ⇒ "https://www.amazon.com/dp/B08KTZ8249"
----

NOTE: While this doesn’t look like much of an improvement, the full string takes 38 bytes to encode,
but the macro invocation takes as few as 12 bytes.


=== Special Form: `*literal*`

To explain more carefully, when a template-expression is syntactically an S-expression, its first
element must be a symbol that matches either a set of keywords denoting the special forms, or the
name of a previously-defined macro.  The interpretation of the S-expression’s remaining elements
depends on how the symbol resolves.  In the case of macro invocations, we’ve seen above that the
following elements are (so far!) arbitrary template expressions, but for special forms that’s not
always the case. The `*literal*` form makes this clear:

[{mrk}]
----
(*public* USD_price [dollars] (price dollars (*literal* USD)))
----
----
(:USD_price 12.99) ⇒ { amount: 12.99, currency: USD }
----

In this template, we can’t just write `(price dollars USD)` because the symbol `USD` would be
treated as an unbound variable reference and a syntax error, so we turn it into literal data by
“escaping” it with `*literal*`.

TIP: Our documents use bold typewriter face to distinguish special forms and keywords from symbols
referencing macros and parameters.

The critical point is that special forms are “special” precisely because they cannot be expressed
as macros and must therefore receive bespoke syntactic treatment.  Since the elements of
macro-invocation expressions are themselves expressions, when you want something to _not_ be
evaluated that way, it must be a special form.

Finally, these special forms are part of the template language itself, and are not visible to
encoded data: the E-expression `(:literal foo)` must necessarily refer to some user-defined macro
named `literal`, not to this special form.  (There’s also no need for such a form in
E-expressions, because in that context symbols and S-expressions are not “evaluated”, and
everything is literal except for E-expressions (which are not data, but encoding artifacts).)


=== Parameter Types

In our examples so far, the macro signatures have been simple lists of parameter names, and each
parameter accepts a value of any type.  But this is often undesirable, since the resulting output
could be schematically malformed, or worse(?), macro-expansion could fail in hard-to-diagnose ways:

[{mrk}]
----
(:detail_page_url [true]) ⇒ _**error**: make_string expects a string_
----

This E-expression cannot be expanded because `make_string` requires its arguments to be textual
values, and `[true]` is not a string or symbol.  But this failure happens within the
implementation of `detail_page_url`, not the point where the error occurred.  In this example
those points are only one step removed, but it’s not hard to imagine macros where the stack is
deep enough to make diagnosis quite difficult.

To detect problems close to their source, macro signatures can declare type constraints on their parameters:

[{mrk}]
----
(*public* detail_page_url
  [(*string* asin)]
  (website_url (make_string "dp/" asin)))
----

Here we constrain the `asin` parameter to produce a string so the blame is more clear:

[{mrk}]
----
(:detail_page_url [true]) ⇒ _**error**: detail_page_url expects a string_
----

These types also serve a second, perhaps more impactful, purpose: they can allow the binary
encoding to be more compact by omitting type information or using fixed-width values.

This example reveals additional syntax for parameter declarations.  So far, a parameter was
declared by a symbol denoting its name, now we have an S-expression pairing a type and a name.
In this context the types include all the normal “concrete” Ion types, abstract
supertypes like `*number*`, `*text*`, and `*lob*`, and the unconstrained “top type” `*any*`.
The latter is the default type, so the signature `[foo]` is equivalent to `[(*any* foo)]` meaning
that the parameter `foo` accepts any value.


=== Cardinality: Rest Parameters

Sometimes we want a macro to accept an arbitrary number of arguments, in particular _all the rest
of them_.  The `make_string` macro is one of those, concatenating all of its arguments into a
single string:

----
(:make_string)                 ⇒ ""
(:make_string "a")             ⇒ "a"
(:make_string "a" "b"    )     ⇒ "ab"
(:make_string "a" "b" "c")     ⇒ "abc"
(:make_string "a" "b" "c" "d") ⇒ "abcd"
----

To make this work, the definition of make_string is effectively:

[{mrk}]
----
(*public* make_string [(*text \...* parts)] …)
----

This says that `parts` is a _rest parameter_ accepting zero or more arguments of type `*text*`.
The `*\...*` modifier can only occur on the last parameter, declaring that “all the rest” of the
arguments will be passed to that one name.

NOTE: The Ion grammar treats identifiers like `text` and operators like `\...` as separate tokens
even when juxtaposed like `text\...`. The template language syntax leverages that, and we’ll use the
latter representation from now on.

At this point our distinction between parameters and arguments starts showing its value, since
they are no longer one-to-one: this macro with one parameter can be invoked with one argument, or
twenty, or none. We describe the acceptable number of arguments for a parameter as its
_cardinality_.  In the examples so far, all parameters have had _exactly-one_ cardinality, while
`parts` has _zero-or-more_ cardinality.  We’ll see additional cardinalities soon!


=== Templates Transform Streams

Rest-parameters raise a question: what happens when a template references a parameter that was
given more than one argument?  The answer revolves around a unique aspect of Ion’s macro system
and template language: the inputs to and the output from a macro are streams of values,
constrained in size by cardinality declarations.  When a macro is invoked, each parameter is
bound to a stream of values, and the use of the parameter’s name is a reference to that stream,
not to a specific value.  The declared cardinality of a parameter constrains the number of
elements produced by its stream, and is verified by the macro expansion system.

More generally, the template language itself is stream-oriented, and the results of template
expressions are streams.  While most expression forms produce exactly-one value, various macros
and special forms can produce zero or more values.

We have everything we need to illustrate, via another system macro, `values`:

[{mrk}]
----
(*public* values [(*any\...* vals)] vals)
----
----
(:values 1)           ⇒ 1
(:values 1 true null) ⇒ 1 true null
(:values)             ⇒ _nothing_
----

Here we finally see a macro that produces something other than exactly one value!  The `values`
macro accepts any number of arguments and returns their values, effectively a multi-value
identity function.  We can use this to explore how streams combine in E-expressions.


==== Inlining in encoded data

When an E-expression occurs at top-level or within a list or S-expression, the results are
inlined into the surrounding container:

----
[first, (:values), last]          ⇒ [first, last]
[first, (:values "middle"), last] ⇒ [first, "middle", last]
(first (:values left right) last) ⇒ (first left right last)
----

This also applies in many (but not all!) argument positions inside an E-expression:

----
(first (:values (:values left right) (:values)) last) => (first left right last)
----

Note that each argument-expression always maps to one parameter, even when that expression
returns too-few or too-many values.

[{mrk}]
----
(*public* reverse [a, b] [b, a])
----

[{mrk}]
----
(:reverse (:values 5 USD))   ⇒ _**error**: 'reverse' expects 2 arguments, given 1_
(:reverse 5 (:values) USD)   ⇒ _**error**: 'reverse' expects 2 arguments, given 3_
(:reverse (:values 5 6) USD) ⇒ _**error**: argument 'a' expects 1 value, given 2_
----

In this example, the parameters expect exactly one argument, producing exactly one value.  When
the cardinality allows multiple values, then arguments are inlined into a single stream.  We saw
this (rather subtly) above in the nested use of `values`, but can also illustrate using the
rest-parameter to `make_string`, using indentation to clarify the nesting:

----
(:make_string (:values)
              a
              (:values b
                       (:values c)
                       d)
              e)                   ⇒ "abcde"
----

Inlining within sequences is straightforward, but structs are trickier due to their key/value
nature.  When used in field-value position, each result from a macro is bound to the field-name
independently, leading to the field being repeated or even absent:

----
{ name: (:values) }     ⇒ { }
{ name: (:values v) }   ⇒ { name: v }
{ name: (:values v w) } ⇒ { name: v, name: w }
----

An E-expression can even be used in place of a key-value pair, in which case it must return
structs, which are merged into the surrounding container:

[{mrk}]
----
{ a:1, (:values), z:3 }             ⇒ { a:1, z:3 }
{ a:1, (:values {}), z:3 }          ⇒ { a:1, z:3 }
{ a:1, (:values {b:2}), z:3 }       ⇒ { a:1, b:2, z:3 }
{ a:1, (:values {b:2} {z:3}), z:3 } ⇒ { a:1, b:2, z:3, z:3 }

{ a:1, (:values key "value") } ⇒ _**error**: struct expected for inlining into struct_
----


==== Inlining in template expressions

The preceding examples demonstrate inlining of E-expressions into encoded data, but similar
stream-inlining occurs within the template language, making it trivial to convert a stream to a
list:

[{mrk}]
----
(*public* int_list
  [(**int\...** vals)]
  [ vals ])
(*public* clumsy_bag
  [(**any\...** elts)]
  { '': elts })
----
----
(:int_list)   ⇒ []
(:clumsy_bag) ⇒ {}

(:int_list 1 2 3)    ⇒ [1, 2, 3]
(:clumsy_bag true 2) ⇒ {'':true, '':2}
----

As a reminder, streams and lists are different, there’s no flattening involved, and declared
types are verified:

[{mrk}]
----
(:int_list 1 [2] 3) ⇒ _**error**: [2] is not an int_
----

TODO: demonstrate inlining in TDL macro invocations


=== Mapping Templates Over Streams

Another way to produce a stream is via a mapping form. The `*for_each*` special form evaluates a
template once for each value provided by a macro parameter.  Each time, the parameter name is
shadowed and rebound to the next value on the stream.

[{mrk}]
----
(*public* prices
  [(*symbol* currency), (*number\...* amount)]
  (*for_each* amount
    (price amount currency)))
----
----
(:prices GBP 10 9.99 12.)
⇒ {amount:10, currency:GBP} {amount:9.99, currency:GBP} {amount:12., currency:GBP}
----

TODO: Consider the more-general binding form


=== Empty Streams: `*void*`

To wrap up our discussion of streams, we have another important built-in macro: `void` accepts
no values and produces no value. In other words, it’s a constant, the empty stream:

----
(:int_list (:void)) ⇒ []
(:int_list 1 (:void) 2) ⇒ [1, 2]
[(:void)]   ⇒ []
{a:(:void)} ⇒ {}
----

When used as a macro argument, a `void` invocation (like any other expression) counts as one
argument, albeit one with no value(s).

[{mrk}]
----
(:pi (:void)) ⇒ _**error**: 'pi' expects 0 arguments, given 1_
----

Void is important because we need something outside the Ion data model to express that Ion data
doesn't exist.  We can’t use null because `null` is a value!  In much the same way that Ion
differentiates a null-field from an absent field (_e.g._, `{a:null}` versus `{}`), macros need to
differentiate the absence of value from all other values in the Ion data model.

We’ll use the term _void_ most accurately as a synonym for “empty stream”, but you might catch us
talking as if void were a value, when it’s actually no value at all.  We’ll even mint the word
_voidable_ to describe parameters that can accept zero values, like the ``*\...*``s above. This
neologism will prove useful, you’ll see.

To really nail the point home: the special-case E-expression `(:)` is synonymous with `(:void)`
and exists solely as a more-pleasant argument expression for voidable parameters.


=== Other Cardinalities

For a language that’s thoroughly stream-oriented, rest-parameters don’t offer much flexibility
with respect to cardinality.  The `*\...*` modifier can only be the final parameter, meaning that
only that parameter can be invoked with more than one subexpression and produce more than one
value.  So far other parameters must have exactly-one value, which is fairly limiting.

In fact, the macro system provides four distinct cardinality constraints: exactly-one,
zero-or-one, zero-or-more, and one-or-more.  They each have modifier symbols that can be used in
signatures, namely `*!*`, `*?*`, `***`, and `*+*`. The former is the default, so the signatures
`[arg]`, `[(*any* arg)]`, and `[(*any!* arg)]` are all equivalent.


==== zero-or-one

The zero-or-one cardinality, denoted in signatures by the modifier `*?*`, is much like the default
exactly-one cardinality, except the parameter is voidable.  That is, it accepts an empty-stream
argument as a way to denote an absent parameter.

[{mrk}]
----
(*public* temperature
  [(*decimal* degrees), (*symbol?* scale)]
  {degrees: degrees, scale: scale})
----

Since the scale is voidable, we can pass it void:

----
(:temperature 96 F)    ⇒ {degrees:96, scale:F}
(:temperature 283 (:)) ⇒ {degrees:283}
----

Note that the result’s `scale` field has disappeared because no value was provided.  It would be
more useful to fill in a default value, and to do that we introduce another special form that can
detect void:

[{mrk}]
----
(*public* temperature
  [(*decimal* degrees), (*symbol?* scale)]
  {degrees: degrees, scale: (*if_void* scale (*literal* K) scale)})
----
----
(:temperature 96 F)    ⇒ {degrees:96,  scale:F}
(:temperature 283 (:)) ⇒ {degrees:283, scale:K}
----

The `*if_void*` form is if/then/else syntax testing stream emptiness. It has three sub-expressions,
the first being a stream to check. If and only if that stream is void (_i.e._, it produces no
values), the second sub-expression is expanded and its results are returned by the `*if_void*`
expression. Otherwise, it produces at least one value, so the third sub-expression is expanded and
returned.

NOTE: Exactly one branch is expanded, because otherwise the void stream might be used in a context
that requires a value, resulting in an errant expansion error.

To refine things a bit further, trailing voidable arguments can be omitted entirely:

----
(:temperature 283) ⇒ {degrees:283, scale:K}
----


==== zero-or-more

A zero-or-more `***` parameter is identical in meaning to our friend `*\...*` from the perspective
of its template, but it can be used in any position, not just last place.

[{mrk}]
----
(*public* prices
  [(*number** amount), (*symbol* currency)]
  (*for_each* amount
    (price amount currency)))
----

From the perspective of the invoker, the calling convention is different since the “all the rest”
convention can’t be used to draw the boundaries of the stream.  Instead, we use a list or
S-expression as a delimiting container to group the applicable sub-expressions:

[{mrk}]
----
(:prices () JPY)         ⇒ _void_
(:prices (10  9.99) GBP) ⇒ {amount:10, currency:GBP} {amount:9.99, currency:GBP}
(:prices [10, 9.99] GBP) ⇒ {amount:10, currency:GBP} {amount:9.99, currency:GBP}
----

The delimiting sequence is effectively shorthand for a `values` expression, but arbitrary
expressions are not allowed:

[{mrk}]
----
(:prices (:values 10 9.99 12.) GBP) ⇒ _**error**: delimiting list or sexp expected_
(:prices (:) GBP)                   ⇒ _**error**: delimiting list or sexp expected_
----

That’s because the binary representation of these parameters uses a tagless format for these
delimiters to keep the common case as dense as possible, and it’s not possible to replace that
container with a macro invocation.  The text form mirrors that limitation, but you can always
call a macro inside the delimiter, with no loss of generality:

----
(:prices [(:values 10)] GBP) ⇒ {amount:10, currency:GBP}
----

Note that the delimiter is required even for single values, again for consistency but more
importantly to avoid ambiguity.  Consider this macro:

[{mrk}]
----
(*public* ouch [(*list** stuff)] …)
----

In the E-expression `(:ouch [])`  is that list the delimiting container, or the sole input value?
When expanding the E-expression does `stuff` produce void, or a single empty list?  `***`-arguments
require a delimiting container precisely so there’s no ambiguity, regardless of the element type,
and the answer is that `stuff` is void.

Within the delimiting container, the invocation can have any number of values and/or macro
invocations.  The macro parameter produces the results of those expressions, concatenated into a
single stream, and the expander verifies that each value on that stream is acceptable by the
parameter’s declared type.

----
(:prices (1 (:values 2 3) 4) GBP) ⇒ {amount:1, currency:GBP}
                                    {amount:2, currency:GBP}
                                    {amount:3, currency:GBP}
                                    {amount:4, currency:GBP}
----


==== one-or-more

A one-or-more `*+*` parameter works just like `***` except the resulting stream must produce at
least one value.  To continue abusing our prices example:

[{mrk}]
----
(*public* prices
  [(*number+* amount), (*symbol* currency)]
  (*for_each* amount
    (price amount currency)))
----

[{mrk}]
----
(:prices () JPY) ⇒ _**error**: at least one value expected for + parameter_
(:prices [99] EUR)               ⇒ {amount:99, currency:EUR}
(:prices \((:) (:values 99)) EUR) ⇒ {amount:99, currency:EUR}
----

Note that among the delimited expressions, empty results are fine, as long as their concatenation
produces one or more values.


=== Optional Arguments

When a trailing parameter is voidable, an invocation can omit its corresponding argument, as long
as no following parameter is being given a value.  We’ve seen this as applied to rest-parameters,
but it also applies to `*?*` and `***` cardinality:

[{mrk}]
----
(*public* optionals
  [(**any* **a), (*any?* b), (*any!* c), (*any** d), (*any?* e), (*any\...* f)]
  (make_list a b c d e f))
----

Since `d`, `e`, and `f` are all voidable, they can be omitted by invokers.  But `c` is required so
`a` and `b` must always be present, at least as an empty delimiter:

----
(:optionals [] (:) for_c) ⇒ [for_c]
----

Now `c` receives the symbol `for_c` while the other parameters are all void.  If we want to provide
just `e`, then we must also provide a delimiter for `d`:

----
(:optionals [] (:) for_c () for_e) ⇒ [for_c, for_e]
----


=== Tagless and Fixed-Width Types

It’s time to shift gears to discuss a feature that primarily benefits binary-encoded data:
tagless types.

Those familiar with binary Ion will understand that the encoding of every value starts off with a
“type tag”, an opcode that indicates the data-type of the next value and thus the interpretation
of the following octets of data.  In general, these tags also indicate whether the value has
annotations, and whether it’s null.

These tags are necessary because the Ion data model allows values of any type to be used
anywhere. Ion documents are not schema-constrained: nothing forces any part of the data to have a
specific type or shape.  We call Ion “self-describing” precisely because each value
self-describes its type via a type tag.

This adds considerable overhead throughout the document, which is frustrating when schema
constraints are enforced through some mechanism outside the serializer/deserializer.  It’s worse
when you observe that the overhead for each value also includes length information: encoding an
octet of data takes two octets on the stream.

Ion 1.1 confesses to the impact of this overhead, and the macro system aims to address it by
allowing parameters to have tagless types.  These are semantic subtypes of the concrete types,
constrained such that type tags are not necessary in the binary form.  In general this can shave
4-6 bits off each value, which can add up in aggregate.  In the extreme, that octet of data can
be encoded with no overhead at all.

To define a tagless parameter, add the `*tagless*` modifier to any of the concrete types:

[{mrk}]
----
(*public* point
  [(*tagless int* x), (*tagless int* y)]
  {x: x, y: y})
----
----
(:point 3 17) => {x:3, y:17}
----

The type constraint has no real benefit here in text, as tagless types aim to improve the binary
encoding. TODO talk about binary length improvement.

This density comes at the cost of flexibility.  Tagless types cannot be annotated or null, and
argument values cannot be expressed using macros, like we’ve done before:

[{mrk}]
----
(:point null.int 17)   => _**error**: tagless int does not accept nulls_
(:point a::3 17)       => _**error**: tagless int does not accept annotations_
(:point (:values 1) 2) => _**error**: cannot use macro for a tagless argument_
----

While Ion text syntax doesn’t use tags—the types are built into the syntax—these errors ensure
that a text E-expression can’t express things that can’t be done in the corresponding binary
E-expression.

For more impact, use `*tagless*` with one of a set of additional “binary-only” types: `*uint*`,
`*uint8*`, `*uint16*`, `*uint32*`, `*uint64*`, `*int8*`, `*int16*`, `*int32*`, `*int64*`,
`*float16*`, `*float32*`, and `*float64*`.  This set is called “binary only” because their values
have no unique representation in Ion text: they appear there as normal ints and floats.

[{mrk}]
----
(*public* byte_array
  [(*tagless uint8\...* bytes)]
  [bytes])
----

Invocations of this macro are encoded (more or less) as a plain sequence of octets, because the
macro definition constrains the argument shape such that nothing else is acceptable.  A text
invocation is written using normal ints:

[{mrk}]
----
(:byte_array 0 1 2 3 4 5 6 7 8) => [0, 1, 2, 3, 4, 5, 6, 7, 8]
(:byte_array 9 -10 11)          => _**error**: -10 is not a valid uint8_
(:byte_array 256)               => _**error**: 256 is not a valid uint8_
----
As above, Ion text doesn’t have syntax specifically denoting “8-bit unsigned integers”, so to
keep text and binary capabilities aligned, the parser rejects invocations where an argument value
exceeds the range of the binary-only type.

The use of tagless types brings inherent tradeoffs which requires careful consideration, but in
the right circumstances the density wins can be significant.


=== Macro Shapes

We can now introduce the final kind of input constraint, macro-shaped parameters.  To understand
the motivation, consider modeling a scatter-plot as a list of points:

----
[{x:3, y:17}, {x:395, y:23}, {x:15, y:48}, {x:2023, y:5}, …]
----

Lists like these exhibit a lot of repetition. Since we already have a `point` macro, we can
eliminate a fair amount:

----
[(:point 3 17), (:point 395 23), (:point 15 48), (:point 2023 5), …]
----

This eliminates all the ``x``s and ``y``s, but leaves repeated macro invocations.  We can try to
wrap this in another macro, but we find the type constraints insufficient, since the tightest we
can go is `*struct*`, and things aren’t really any better:

[{mrk}]
----
(*public* scatterplot [(*struct\...* points)]
  [points])
----
----
(:scatterplot (:point 3 17) (:point 395 23) (:point 15 48) (:point 2023 5) …)
----

What we’d like is to build eliminate the `point` calls and just write a stream of pairs, something
like:

----
(:scatterplot (3 17) (395 23) (15 48) (2023 5) …)
----

We can achieve exactly that with a macro-shaped parameter, in which we use the `point` macro as a
pseudo-type:

[{mrk}]
----
(*public* scatterplot [(*point\...* points)]
  [points])
----
----
(:scatterplot (3 17) (395 23) (15 48) (2023 5) …)
=>
[{x:3, y:17}, {x:395, y:23}, {x:15, y:48}, {x:2023, y:5}, …]
----

What’s happening here is that each argument S-expression like `(3 17)` is _implicitly an
E-expression_ invoking the `point` macro.  The argument mirrors the shape of the inner macro,
without repeating its name.  Further, expansion of the implied ``point``s happens automatically,
so the overall behavior is just like the preceding struct-based variant and the `points`
parameter produces a stream of structs.

As the text notation here suggests, macro-shaped parameters are tagless, and the binary form also
elides any opcodes mentioning `point` and just encodes its arguments with minimal delimiting.

Macro types can be combined with any cardinality, following the same rules as before.  Note that
when combined with `***` or `*+*` this requires callers to use two layers of delimiting
containers, and outer delimiter for the parameter-stream as a whole, and an inner delimiter for
each macro instance:

[{mrk}]
----
(*public* scatterplot
  [(*point** points), (*string* x_label), (*string* y_label)]
  { points: [points], x_label: x_label, y_label: y_label })
----
----
(:scatterplot ((3 17) (395 23) (15 48) (2023 5)) "hour" "widgets")
=>
{
  points: [{x:3, y:17}, {x:395, y:23}, {x:15, y:48}, {x:2023, y:5}],
  x_label: "hour",
  y_label: "widgets"
}
----

TODO Describe binary representation

CAUTION: Because these are tagless encodings, we cannot use macros in place of the delimiting
containers, so unfortunately we cannot generate a point or series of points through a macro.


=== Macro return-types

TODO
