[[sec:semantics-conventions]]
== Semantics and Conventions

In this chapter, we will describe the _denotational semantics_ of the Ion data format.  This means we will map the
meaning of Ion syntax to typed, domains in lambda calculus.  This will form the basis using mathematical definitions as
the meaning of Ion data and importantly how computational elements such as symbol tables and template expressions
work.

=== Lambda Calculus Primer

Lambda calculus is a mathematical formalism for computing that introduces anonymous functions (i.e., abstractions or
lambda), terms (i.e., variables), and application (i.e., invocation of functions).  This minimal set of operations and
has been shown to be both turing complete and encode mathematical concepts such as Booleans and natural numbers (and the
operations on them).  It is similarly straightforward to model data types such as _sequences_, _tuples_, _sets_, and
_bags_ using lambda calculus.

With these primitives we define types of values over Lambda calculus as a _domain_.  A _domain_ is a set of values, but
each value knows what type it is. 