[[sec:semantics-templates]]
== Template Expression Semantics

Ion 1.1 introduces the concept of _template expressions_ that _evaluate_ to the Ion data model.  This section covers the
semantics of such expressions and indicates how they should work independent of the three _syntaxes_ that Ion 1.1
specifies.

=== Basic Computation Model

Templates expressions can be thought of as pre-processing computation that produces a stream of Ion data values.  The
result of any given template expression stem:[e] is always a stream of Ion values (i.e., stem:[(:(:v_1, ..., v_n:):)]).
This is necessary to denote the lack of value or multiple values in processing such expressions as distinct from Ion
sequences which themselves are values.  Importantly, streams cannot be nested (unlike `list` and `sexp`) and so streams
cannot be nested within streams.

The Ion value stream (e.g., document) can be thought of as a top-level sequence of template expressions
stem:[bb"top-level"(e_1, ..., e_n)].  The evaluation of these expressions can be described as a flattening of the
resulting stream of each expression into a single top-level value stream.

.Figure {counter:figure-number}. Top-level stream of expressions.
[stem%unbreakable]
++++
(
    (:e_1, sigma:) darr (:(: v_1, ... v_i:):),
    \ ...,
    (:e_n, dot sigma:) darr (:(: v_(n + 1), ..., v_(n + i) :):))
/
(
    (:bb"top-level"(e_1, ..., e_n), sigma:)
    darr
    (:(: v_1, ... v_i, ... v_(n + 1), ..., v_(n + i) :):)
)
++++

Ion value literals are of the abstract form stem:[bb"literal"(v)] and unconditionally evaluate to the
singleton stream of itself:

.Figure {counter:figure-number}. Evaluation of literal Ion values.
[stem%unbreakable]
++++
()
/
(
    (:bb"literal"(v), sigma:)
    darr
    (:(:\ v\ :):)
)
++++

We can use these two rules to explain Ion 1.0 and (non-templated Ion 1.1 value streams) as top-level sequence of
template expressions that comprise only Ion value literals.  It _is not_ the case that an implementation of Ion has to
evaluate such a data stream as described here, but rather this is an _explanation_ of how the data stream is produced
from the syntax of Ion data files (and the Ion template definition language).

Similar to the top-level, Ion 1.1 introduces _quasi-quoted_ literals for containers that can nest expressions within
containers.  The abstract syntax for this is as follows:

.Figure {counter:figure-number}. Evaluation of `list` quasi-literals.
[stem%unbreakable]
++++
(
    (:e_a, sigma:) darr (:(: v_1^a, ... v_n^a :):),
\   (:e_1, sigma:) darr (:(: v_1^1, ..., v_n^1 :):),
\   ...,
\   (:e_n, sigma:) darr (:(: v_1^n, ..., v_n^n :):)
)
/
(
    (:bb"list"(e_a, e_1, ..., e_n), sigma:) 
    darr
    (:(: v_1^a tt"::"\ ...\ tt"::" v_n^a \[ v_1^1, ..., v_n^1, ..., v_1^n, ..., v_n^n \] :):)
)
++++

.Figure {counter:figure-number}. Evaluation of `sexp` quasi-literals.
[stem%unbreakable]
++++
(
    (:e_a, sigma:) darr (:(: v_1^a, ... v_n^a :):),
\   (:e_1, sigma:) darr (:(: v_1^1, ..., v_n^1 :):),
\   ...,
\   (:e_n, sigma:) darr (:(: v_1^n, ..., v_n^n :):)
)
/
(
    (:bb"sexp"(e_a, e_1, ..., e_n), sigma:) 
    darr
    (:(: v_1^a tt"::"\ ...\ tt"::" v_n^a ( v_1^1\ ...\ v_n^1\ ...\ v_1^n\ ...\ v_n^n ) :):)
)
++++

In this case we have a constructor syntax for creating `list` and `sexp` values, and some specified parts of that
syntax are annotations, those values must be textual values (and the syntax can constrain this in practice). 
`struct` follows similarly:

.Figure {counter:figure-number}. Evaluation of `struct` quasi-literals.
[stem%unbreakable]
++++
(
    (:e_a, sigma:) darr (:(: v_1^a, ... v_n^a :):),
\   (:e_1^k, sigma:) darr (:(:\ v_1^k\ :):),
\   (:e_1^v, sigma:) darr (:(: v_1^v, ..., v_n^v :):),
\   ...
)
/
(
    (:bb"struct"(e_a, e_1^k, e_1^v, ...), sigma:) 
    darr
    (:(: v_1^a tt"::"\ ...\ tt"::" {v_1^k : v_1^v, ..., v_1^k : v_n^v, ...} :):)
)
++++

In the above, field names must evaluate to a single textual value (again likely constrained by syntax) and for each
value in the stream associated to a field name, a key/value pair is produced in the resulting `struct` value.

The other type of expression in the basic model are template invocations:

.Figure {counter:figure-number}. Evaluation of arguments and flattening in operator invocation.
[stem%unbreakable]
++++
(
    (:e_1^1, sigma:) darr (:(: v_1^1, ... v_n^1 :):),
\   ...,
\   (:e_n^1, sigma:) darr (:(: v_1^n, ... v_n^n :):),
\   ...,
\   (:e_1^k, sigma:) darr (:(: v_1^k, ... v_n^k :):),
\   ...,
\   (:e_n^k, sigma:) darr (:(: v_1^(k*n), ... v_n^(k*n) :):)
)
/
(
    (: bb"invoke"(tt"opname", e_1^1, ..., e_n^1, ..., e_1^k..., e_n^k), sigma:)
    darr
    (:
        bb"invoke-values"(
            tt"opname",
            (:(: v_1^1, ..., v_n^1, ..., v_1^n, ..., v_n^n :):),
            ...,
            (:(: v_1^k, ..., v_n^k, ..., v_1^(k*n), ..., v_n^(k*n) :):)
        ),
        sigma
    :)
)
++++

Template invocations are functions where its formal parameters are sequences of expressions.  These sequences are
delimited by syntax and guided by the definition of the operator.  When evaluated, each expression in a sequence is
evaluated to a stream of values and flattened into a single stream of values which will be the argument for the formal
parameter.

The operator selected by `opname` is statically defined (the `opname` is a symbolic name determined at compile-time and
not a dynamic parameter). `opname` is part of the state stem:[sigma] and can be configured differently in different
contexts (e.g., as a symbol table is loaded or as a module of template operators are being defined).  These expressions
are evaluated and flattened into a single stream per formal parameter.  It is outside of the scope of this chapter to
describe the semantics how the operator table is loaded (see section *_TBD_*).

Finally the operator function is than invoked with the resulting streams:

.Figure {counter:figure-number}. Evaluation of operator invocation with streams of values per parameter.
[stem%unbreakable]
++++
()
/
(
    (: bb"invoke-values"(tt"opname", s_1, ..., s_n), sigma:)
    darr
    s
)
++++

In the above, `invoke` is the abstract syntax that denotes the invocation with groups of expressions.  `invoke-values`
is the abstract syntax of the invocation of the function where the expression grouping has been resolved and flattened
into streams of values, one per each parameter.  A user never interacts with `invoke-values`, this is an intermediate
rule in the semantics to demonstrate the flattening and the invocation of the operator as a pure function over streams
of values.  Finally, the reduction of `invoke-values` indicates that all invocations evaluate to streams of values.

=== System Template Operators

*_TBD._*  _This section will describe the operational semantics of the system operators._

=== Template Definitions

Ion 1.1, in addition to having syntax for template expansion within the data stream, has a domain specific language
for specifying template operators.  To describe the semantics of these definitions, which parameters and expression
bodies, we will denote an abstract syntax for the function as follows:

.Figure {counter:figure-number}. Function abstract syntax.
[stem%unbreakable]
++++
bb"function"(tt"p"_1, ..., tt"p"_n, e)
++++

In the above, the stem:[tt"p"_1, ..., tt"p"_n] denote the names of the formal parameters, and stem:[e] denotes the
expression body. Furthermore, we can store instances of this abstract syntax as values in the state stem:[sigma].  The
notation stem:[sigma_f\[tt"x" |-> f\]] Will be used to denote a functionally mutated state that adds the operator named
`x` to the operator table bound to the function value stem:[f].

*_TBD._* _Describe the module, the exports, and the definitions themselves._

==== Template Definition Expressions

*_TBD._* _There are expressions that are endemic to template definitions and are otherwise unavailable to template
expansions in the data stream, this section will describe those semantics and specifically deal with the interaction
with the state stem:[sigma] as appropriate (i.e., `void`, `quote`, `if`, `when`, `unless`, `each`)._
